M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sat 29 Jul 2023 01:02:36 PM IST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-29T13:02:36+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X100.0Y-50.0
X100.0Y-98.0
X192.0Y-50.0
X192.0Y-98.0
T0
M30
